# Generated by Django 3.1.7 on 2021-04-01 06:58

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210401_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='article_image/'),
        ),
    ]
