# Generated by Django 3.1.7 on 2021-04-01 07:03

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='media/article_image/'),
        ),
    ]
