# Generated by Django 3.1.7 on 2021-04-01 08:22

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210401_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='image/article_image'),
        ),
    ]
